baseURL = 'https://shahfazal.com/'
languageCode = 'en-us'
title = 'Shahfazal'
theme = 'PaperMod'
paginate = 10

[params]
  author = 'Fazal'
  description = 'ML, Open Data, learning and building things in public.'
  comments = true
[params.profileMode]
  enabled = true
  title = "Shahfazal Mohammed"
  subtitle = "20 years in deterministic software engineering. Now learning what happens when the rules aren't explicit. Building neural nets, and agent evals in public."
[[params.profileMode.buttons]]
  name = "View Projects"
  url = "/projects/"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowSocialICons = true
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/shahfazal"
  [[params.socialIcons]]
    name = "medium"
    url = "https://medium.com/@shahfazal"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/shahfazalmohammed"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 1
  [[menu.main]]
    name = 'Writing'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3
